# Generated by Django 2.2.1 on 2020-06-23 05:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahanagari_Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainNo', models.IntegerField()),
                ('No', models.IntegerField()),
                ('StationName', models.CharField(max_length=50)),
                ('Arrives', models.TimeField()),
                ('Departs', models.TimeField()),
                ('StopTime', models.CharField(max_length=20)),
                ('DistanceTravelled', models.CharField(max_length=20)),
                ('Day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mahanagari_Express_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainNo', models.IntegerField()),
                ('Day', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('RunningStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nagpur_Pune_Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainNo', models.IntegerField()),
                ('No', models.IntegerField()),
                ('StationName', models.CharField(max_length=50)),
                ('Arrives', models.TimeField()),
                ('Departs', models.TimeField()),
                ('StopTime', models.CharField(max_length=20)),
                ('DistanceTravelled', models.CharField(max_length=20)),
                ('Day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nagpur_Pune_Express_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainNo', models.IntegerField()),
                ('Day', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('RunningStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pune_Bsl_Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainNo', models.IntegerField()),
                ('No', models.IntegerField()),
                ('StationName', models.CharField(max_length=50)),
                ('Arrives', models.TimeField()),
                ('Departs', models.TimeField()),
                ('StopTime', models.CharField(max_length=20)),
                ('DistanceTravelled', models.CharField(max_length=20)),
                ('Day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pune_Bsl_Express_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainNo', models.IntegerField()),
                ('Day', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('RunningStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Railwayroute',
            fields=[
                ('trainNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('intermediate_station', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None)),
            ],
        ),
    ]
