# Generated by Django 2.2.1 on 2020-06-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0003_mahanagari_express_booked_nagpur_pune_express_booked_pune_bsl_express_booked_seat_alloc'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('date_of_journey', models.DateField()),
                ('no_of_Seats', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('id_proof', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('class_type', models.CharField(max_length=10)),
                ('birth_preferance', models.CharField(max_length=5)),
            ],
        ),
    ]
