# Generated by Django 2.2.1 on 2020-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0005_auto_20200627_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='train_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
