# Generated by Django 2.2.1 on 2020-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0006_registration_train_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='src_date',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
