# Generated by Django 2.2.1 on 2020-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0007_registration_src_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='medical_status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
