# Generated by Django 2.2.1 on 2020-06-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0008_registration_medical_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=10)),
            ],
        ),
    ]
