# Generated by Django 2.2.1 on 2020-06-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0009_usermob'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwayroute',
            name='src_time',
            field=models.TimeField(default='11:35'),
            preserve_default=False,
        ),
    ]
