# Generated by Django 2.2.1 on 2020-06-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0010_railwayroute_src_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='PNR',
            field=models.IntegerField(default=1000000000),
            preserve_default=False,
        ),
    ]
