# Generated by Django 2.2.1 on 2020-06-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0011_registration_pnr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pune_bsl_express_seat_alloc',
            old_name='Nasik_Road',
            new_name='Nashik_Road',
        ),
    ]
