# Generated by Django 2.2.1 on 2020-06-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0012_auto_20200629_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahanagari_express_booked',
            name='PNR',
            field=models.IntegerField(default=1000000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nagpur_pune_express_booked',
            name='PNR',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pune_bsl_express_booked',
            name='PNR',
            field=models.IntegerField(default=1000000000),
            preserve_default=False,
        ),
    ]
