# Generated by Django 2.2.1 on 2020-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0015_remove_registration_medical'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='medical',
            field=models.ImageField(default='registered', upload_to=''),
            preserve_default=False,
        ),
    ]
