# Generated by Django 2.2.1 on 2020-07-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0016_registration_medical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahanagari_express_seat_alloc',
            old_name='Bhurhanpur',
            new_name='Burhanpur',
        ),
    ]
