# Generated by Django 2.2.1 on 2020-07-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0018_auto_20200701_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahanagari_express_seat_alloc',
            old_name='Khandawa',
            new_name='Khandwa',
        ),
    ]
