# Generated by Django 2.2.1 on 2020-07-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0019_auto_20200701_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahanagari_express_seat_alloc',
            old_name='Narsighpur',
            new_name='Narsinghpur',
        ),
    ]
