# Generated by Django 2.2.1 on 2020-07-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0020_auto_20200701_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahanagari_express_seat_alloc',
            old_name='cheoki',
            new_name='Cheoki',
        ),
    ]
